config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :tickets
  post 'auth_user' => 'authentication#authenticate_user'
  root 'welcome#index'
  get 'welcome/index'

  resources :users
  resources :tickets

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
  protect_from_forgery with: :null_session

  attr_reader :current_user

  protected
  def authenticate_request!
    unless user_id_in_token?
      render json: {errors:['Not Authenticated']}, status: :unauthorized
      return
    end
    @current_user = User.find(auth_token[:user_id])
  rescue
    render json: {errors:['Not Authenticated']}, status: :unauthorized
  end

  private
  def http_token
    @http_token ||= if request.headers['Authorization'].present?
      request.headers['Authorization'].split(' ').last
    end
  end

  def auth_token
    @auth_token ||= JsonWebToken.decode(http_token)
  end

  def user_id_in_token?
    http_token && auth_token && auth_token[:user_id].to_i
  end
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  def authenticate_user
    user = User.find_for_database_authentication(email: params[:email])
    if user.valid_password?(params[:password])
      render json: payload(user)
    else
      render json: {errors: ['Invalid Username/Password: wrong p[assword']}, status: :unauthorized
    end
  rescue
    render json: {errors: ['Invalid Username/Password: not found']}, status: :unauthorized
  end

  private

  def payload(user)

    return nil unless user and user.id
    #make a hash with token data
    info = {name: user.name, 
      email: user.email,
      #it will be valid for 18 hours
      expires:(DateTime.now.to_time + 68400)  
    }
    #put token into hash and return
    info.merge!(access_token: JsonWebToken.encode(info))
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:login, :name, :password, :password_confirmation, :loginPhone, :email, :current_password)
    #params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:login, :name, :password, :password_confirmation, :loginPhone, :email, :current_password)
    #params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
    respond_to do |format|
      format.html
      format.json { render json: @users }
    end
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:body, :service, :ipaddress, :contact, :contact_phone, :user_id, :employee_id, :massive)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    respond_to do |format|
      format.html
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:login, :name, :password, :password_confirmation, :loginPhone, :email)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  #before_filter :authenticate_request!

  def index
    ##render json: {'logged_in' => true}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru">
<head>
    <title>ITS портал</title>
    <link rel="icon" type="image/vnd.microsoft.icon" href="assets/favicon.ico" />

    <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Roboto:400,500,700,400italic'>

    
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<script src="https://use.fontawesome.com/ff9b27fab1.js"></script>
</body>
</html>

app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="field">
    <%= f.label :service %><br>
    <%= f.number_field :service %>
  </div>
  <div class="field">
    <%= f.label :ipaddress %><br>
    <%= f.text_field :ipaddress %>
  </div>
  <div class="field">
    <%= f.label :contact %><br>
    <%= f.text_field :contact %>
  </div>
  <div class="field">
    <%= f.label :contact_phone %><br>
    <%= f.text_field :contact_phone %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :employee_id %><br>
    <%= f.number_field :employee_id %>
  </div>
  <div class="field">
    <%= f.label :massive %><br>
    <%= f.check_box :massive %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tickets</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Service</th>
      <th>Ipaddress</th>
      <th>Contact</th>
      <th>Contact phone</th>
      <th>User</th>
      <th>Employee</th>
      <th>Massive</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.body %></td>
        <td><%= ticket.service %></td>
        <td><%= ticket.ipaddress %></td>
        <td><%= ticket.contact %></td>
        <td><%= ticket.contact_phone %></td>
        <td><%= ticket.user_id %></td>
        <td><%= ticket.employee_id %></td>
        <td><%= ticket.massive %></td>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form' %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @ticket.body %>
</p>

<p>
  <strong>Service:</strong>
  <%= @ticket.service %>
</p>

<p>
  <strong>Ipaddress:</strong>
  <%= @ticket.ipaddress %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @ticket.contact %>
</p>

<p>
  <strong>Contact phone:</strong>
  <%= @ticket.contact_phone %>
</p>

<p>
  <strong>User:</strong>
  <%= @ticket.user_id %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @ticket.employee_id %>
</p>

<p>
  <strong>Massive:</strong>
  <%= @ticket.massive %>
</p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :login %><br>
    <%= f.text_field :login %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>  
  <div class="field">
    <%= f.label :loginPhone %><br>
    <%= f.text_field :loginPhone %>
  </div>

  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Login</th>
      <th>Email</th>            
      <th>Name</th>
      <th>Password</th>
      <th>Loginphone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.login %></td>
        <td><%= user.email %></td>        
        <td><%= user.name %></td>
        <td><%= user.password %></td>
        <td><%= user.loginPhone %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Login:</strong>
  <%= @user.login %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Loginphone:</strong>
  <%= @user.loginPhone %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<body ng-app="itsApp" layout="column" ng-cloak ng-controller="layoutCtrl as lc">
    <header>
        <md-toolbar layout="row" class="md-whiteframe-3dp" style="align-items:center;">
            <md-button class="menu md-warn" hide-gt-sm ng-click="ul.toggleList()" aria-label="Show User List">
                <md-icon md-svg-icon="menu"></md-icon>
            </md-button>
            <img src="assets/its.png" alt="ITS logo" height="64px" />
            <h1>Портал</h1>
            <span flex="" class="flex"></span>
            <div class="its-menu-right" ng-switch="lc.loggedin()">
                <a ng-switch-when="false" class="waves-effect waves-light" href="#!/login" ui-sref="login"><i class="fa fa-sign-in" aria-hidden="true"></i><span class="zf-its-nav-text">Вход</span></a>
                <span ng-switch-when="true">{{lc.user().name}}</span>
            </div>
        </md-toolbar>
    </header>
    <section flex layout="row">
        <aside>
            <md-sidenav md-is-locked-open="$mdMedia('gt-sm')" class="md-whiteframe-3dp" md-component-id="left" ng-click="ul.toggleList()" style="margin-right:5px">

                <md-button ng-if="lc.loggedin()" class="md-primary md-raised" new-ticket-btn>Новая заявка</md-button>
                <md-list-item ng-repeat="menuitem in menuitems" ng-click="goToState(menuitem)" class="noright">
                    <p>{{ menuitem.name }}</p>
                </md-list-item>


            </md-sidenav>
        </aside>
        <main class="flex-noshrink">
            <md-content flex id="content">
                <ui-view></ui-view>

            </md-content>
        </main>
    </section>